import React, { useState } from "react";
import { 
  User, Briefcase, Code, BookOpen, BarChart, Calendar, 
  UserCheck, Terminal, Brain, Compass, HelpCircle, ClipboardCheck, Check, Copy, ArrowLeft
} from "lucide-react";
import { PreparationRecord } from "../types";

interface ResultViewProps {
  record: PreparationRecord;
  onBack: () => void;
}

type TabType = "hr" | "technical" | "coding" | "aptitude" | "roadmap" | "tips";

export default function ResultView({ record, onBack }: ResultViewProps) {
  const [activeTab, setActiveTab] = useState<TabType>("hr");
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);
  
  // Track selected answers for aptitude questions
  const [selectedAnswers, setSelectedAnswers] = useState<Record<number, string>>({});

  const { studentName, jobRole, programmingLanguage, topic, difficultyLevel, aiResponse, createdDate } = record;

  const handleCopyCode = (code: string, index: number) => {
    navigator.clipboard.writeText(code);
    setCopiedIndex(index);
    setTimeout(() => setCopiedIndex(null), 2000);
  };

  const handleSelectOption = (questionId: number, optionLetter: string) => {
    setSelectedAnswers((prev) => ({
      ...prev,
      [questionId]: optionLetter
    }));
  };

  const formattedDate = new Date(createdDate).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit"
  });

  const tabItems: { id: TabType; label: string; icon: React.ReactNode }[] = [
    { id: "hr", label: "HR Interview", icon: <UserCheck className="h-4 w-4" /> },
    { id: "technical", label: "Technical Q&A", icon: <BookOpen className="h-4 w-4" /> },
    { id: "coding", label: "Coding Lab", icon: <Terminal className="h-4 w-4" /> },
    { id: "aptitude", label: "Aptitude Quiz", icon: <Brain className="h-4 w-4" /> },
    { id: "roadmap", label: "Learning Roadmap", icon: <Compass className="h-4 w-4" /> },
    { id: "tips", label: "Prep Tips", icon: <ClipboardCheck className="h-4 w-4" /> }
  ];

  return (
    <div className="space-y-6" id="result-view-container">
      {/* Back Button and Heading */}
      <div className="flex items-center justify-between border-b border-slate-200 pb-4">
        <button
          onClick={onBack}
          className="flex items-center gap-1.5 rounded-lg border border-slate-200 px-3.5 py-1.5 text-sm font-medium text-slate-600 shadow-sm transition hover:bg-slate-50 hover:text-slate-900"
          id="btn-back-to-form"
        >
          <ArrowLeft className="h-4 w-4" />
          Back to Generator
        </button>
        <span className="flex items-center gap-1 text-xs text-slate-500 font-medium">
          <Calendar className="h-3.5 w-3.5" />
          {formattedDate}
        </span>
      </div>

      {/* Profile Summary Card */}
      <div className="overflow-hidden rounded-2xl border border-indigo-100 bg-gradient-to-r from-indigo-50/70 to-violet-50/50 p-6 shadow-sm">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2">
              <span className="rounded-full bg-indigo-100 px-2.5 py-0.5 text-xs font-semibold text-indigo-700 uppercase tracking-wider">
                Candidate Profile
              </span>
            </div>
            <h3 className="mt-1.5 text-2xl font-black text-slate-900">{studentName}</h3>
            <p className="text-sm text-slate-600">Customized preparation report generated by Gemini AI.</p>
          </div>

          <div className="grid grid-cols-2 gap-4 rounded-xl bg-white p-4 border border-slate-100 shadow-xs sm:grid-cols-4 md:w-auto">
            <div className="space-y-1">
              <span className="flex items-center gap-1 text-xs font-semibold uppercase tracking-wider text-slate-400">
                <Briefcase className="h-3 w-3" /> Job Role
              </span>
              <p className="font-sans font-bold text-slate-800 text-sm">{jobRole}</p>
            </div>
            <div className="space-y-1">
              <span className="flex items-center gap-1 text-xs font-semibold uppercase tracking-wider text-slate-400">
                <Code className="h-3 w-3" /> Language
              </span>
              <p className="font-mono font-bold text-slate-800 text-sm">{programmingLanguage}</p>
            </div>
            <div className="space-y-1">
              <span className="flex items-center gap-1 text-xs font-semibold uppercase tracking-wider text-slate-400">
                <BookOpen className="h-3 w-3" /> Focus Topic
              </span>
              <p className="font-sans font-bold text-slate-800 text-sm truncate max-w-[140px]" title={topic}>
                {topic}
              </p>
            </div>
            <div className="space-y-1">
              <span className="flex items-center gap-1 text-xs font-semibold uppercase tracking-wider text-slate-400">
                <BarChart className="h-3 w-3" /> Level
              </span>
              <p className={`font-sans font-bold text-sm ${
                difficultyLevel === "Easy" ? "text-green-600" : difficultyLevel === "Medium" ? "text-amber-600" : "text-red-600"
              }`}>{difficultyLevel}</p>
            </div>
          </div>
        </div>
      </div>

      {/* Tabs navigation */}
      <div className="border-b border-slate-200">
        <div className="flex overflow-x-auto pb-px scrollbar-none gap-2">
          {tabItems.map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`flex items-center gap-2 whitespace-nowrap border-b-2 px-4 py-3 text-sm font-semibold transition-all duration-200 ${
                activeTab === tab.id
                  ? "border-indigo-600 text-indigo-600"
                  : "border-transparent text-slate-500 hover:border-slate-300 hover:text-slate-800"
              }`}
              id={`tab-btn-${tab.id}`}
            >
              {tab.icon}
              {tab.label}
            </button>
          ))}
        </div>
      </div>

      {/* Active Tab Panel */}
      <div className="min-h-[400px]">
        {/* HR QUESTIONS TAB */}
        {activeTab === "hr" && (
          <div className="space-y-6" id="panel-hr-questions">
            <div className="flex items-center gap-2">
              <h4 className="text-lg font-bold text-slate-900">HR Interview Questions</h4>
              <span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs font-bold text-slate-600">5 Questions</span>
            </div>

            <div className="space-y-4">
              {aiResponse.hrQuestions?.map((q) => (
                <div key={q.id} className="rounded-xl border border-slate-100 bg-white p-5 shadow-xs hover:border-indigo-50 transition duration-150">
                  <div className="flex gap-3">
                    <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-indigo-50 text-xs font-bold text-indigo-600">
                      {q.id}
                    </span>
                    <div className="space-y-3">
                      <h5 className="font-sans font-bold text-slate-900 text-base leading-snug">{q.question}</h5>
                      <div className="rounded-lg bg-indigo-50/30 p-4 border border-indigo-50/50">
                        <span className="text-[10px] font-black uppercase tracking-wider text-indigo-600 block mb-1">
                          Placement Trainer's Response Strategy:
                        </span>
                        <p className="text-sm leading-relaxed text-slate-600 font-normal">{q.tips}</p>
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* TECHNICAL QUESTIONS TAB */}
        {activeTab === "technical" && (
          <div className="space-y-6" id="panel-technical-questions">
            <div className="flex items-center gap-2">
              <h4 className="text-lg font-bold text-slate-900">Technical Interview Q&A</h4>
              <span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs font-bold text-slate-600">5 Questions</span>
            </div>

            <div className="space-y-4">
              {aiResponse.technicalQuestions?.map((q) => (
                <div key={q.id} className="rounded-xl border border-slate-100 bg-white p-5 shadow-xs hover:border-indigo-50 transition duration-150">
                  <div className="flex gap-3">
                    <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-violet-50 text-xs font-bold text-violet-600">
                      {q.id}
                    </span>
                    <div className="space-y-3 w-full">
                      <h5 className="font-sans font-bold text-slate-900 text-base leading-snug">{q.question}</h5>
                      <div className="rounded-lg bg-slate-50 p-4 border border-slate-100">
                        <span className="text-[10px] font-black uppercase tracking-wider text-slate-500 block mb-1.5">
                          Model Concept Answer:
                        </span>
                        <p className="text-sm leading-relaxed text-slate-700 whitespace-pre-wrap font-sans">
                          {q.sampleAnswer}
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* CODING LAB TAB */}
        {activeTab === "coding" && (
          <div className="space-y-6" id="panel-coding-questions">
            <div className="flex items-center gap-2">
              <h4 className="text-lg font-bold text-slate-900">Coding Challenges</h4>
              <span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs font-bold text-slate-600">3 Coding Questions</span>
            </div>

            <div className="space-y-6">
              {aiResponse.codingQuestions?.map((q, index) => (
                <div key={q.id || index} className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-xs">
                  {/* Problem header */}
                  <div className="flex items-center justify-between border-b border-slate-100 bg-slate-50 px-5 py-3.5">
                    <div className="flex items-center gap-2.5">
                      <span className="flex h-6.5 w-6.5 items-center justify-center rounded-full bg-emerald-100 text-xs font-bold text-emerald-800">
                        {q.id || (index + 1)}
                      </span>
                      <h5 className="font-sans font-black text-slate-900 text-base">{q.title}</h5>
                    </div>
                  </div>

                  {/* Problem details */}
                  <div className="p-5 space-y-4">
                    <div className="space-y-1">
                      <span className="text-[10px] font-black uppercase tracking-wider text-slate-400">Problem Description</span>
                      <p className="text-sm leading-relaxed text-slate-700 font-sans">{q.problemDescription}</p>
                    </div>

                    <div className="grid gap-4 sm:grid-cols-2">
                      <div className="space-y-1 bg-slate-50/50 p-3 rounded-lg border border-slate-100">
                        <span className="text-[10px] font-black uppercase tracking-wider text-slate-400">Input Format</span>
                        <p className="text-xs text-slate-600 leading-relaxed">{q.inputFormat}</p>
                      </div>
                      <div className="space-y-1 bg-slate-50/50 p-3 rounded-lg border border-slate-100">
                        <span className="text-[10px] font-black uppercase tracking-wider text-slate-400">Output Format</span>
                        <p className="text-xs text-slate-600 leading-relaxed">{q.outputFormat}</p>
                      </div>
                    </div>

                    {/* Sample IO */}
                    <div className="grid gap-4 sm:grid-cols-2">
                      <div className="space-y-1">
                        <span className="text-[10px] font-black uppercase tracking-wider text-slate-400">Sample Input</span>
                        <pre className="rounded-lg bg-slate-950 p-3 font-mono text-xs text-emerald-400 overflow-x-auto whitespace-pre">
                          {q.sampleInput}
                        </pre>
                      </div>
                      <div className="space-y-1">
                        <span className="text-[10px] font-black uppercase tracking-wider text-slate-400">Sample Output</span>
                        <pre className="rounded-lg bg-slate-950 p-3 font-mono text-xs text-emerald-400 overflow-x-auto whitespace-pre">
                          {q.sampleOutput}
                        </pre>
                      </div>
                    </div>

                    {/* Starter code with copy button */}
                    <div className="space-y-1">
                      <div className="flex items-center justify-between">
                        <span className="text-[10px] font-black uppercase tracking-wider text-slate-400">
                          {programmingLanguage} Boilerplate Template
                        </span>
                        <button
                          onClick={() => handleCopyCode(q.starterCode, index)}
                          className="flex items-center gap-1 text-xs font-semibold text-indigo-600 hover:text-indigo-800 transition-colors"
                        >
                          {copiedIndex === index ? (
                            <>
                              <Check className="h-3.5 w-3.5 text-green-500" />
                              Copied!
                            </>
                          ) : (
                            <>
                              <Copy className="h-3.5 w-3.5" />
                              Copy Code
                            </>
                          )}
                        </button>
                      </div>
                      <pre className="rounded-lg bg-slate-950 p-4 font-mono text-xs text-slate-300 overflow-x-auto leading-relaxed border border-slate-800 whitespace-pre">
                        {q.starterCode}
                      </pre>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* APTITUDE QUIZ TAB */}
        {activeTab === "aptitude" && (
          <div className="space-y-6" id="panel-aptitude-questions">
            <div className="flex items-center gap-2">
              <h4 className="text-lg font-bold text-slate-900">Aptitude Assessment</h4>
              <span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs font-bold text-slate-600">5 Questions</span>
            </div>

            <p className="text-sm text-slate-500 italic">Test your quantitative and logical abilities below. Click on an option to check if your solution is correct.</p>

            <div className="space-y-6">
              {aiResponse.aptitudeQuestions?.map((q) => {
                const userSelected = selectedAnswers[q.id];
                const isCorrect = userSelected === q.correctAnswer;
                
                return (
                  <div key={q.id} className="rounded-xl border border-slate-200 bg-white p-5 shadow-xs">
                    <div className="flex gap-3">
                      <span className="flex h-6.5 w-6.5 shrink-0 items-center justify-center rounded-full bg-amber-50 text-xs font-bold text-amber-700 border border-amber-100">
                        {q.id}
                      </span>
                      <div className="space-y-4 w-full">
                        <h5 className="font-sans font-bold text-slate-900 text-base leading-snug">{q.question}</h5>
                        
                        {/* Interactive Options Grid */}
                        <div className="grid gap-3 sm:grid-cols-2">
                          {q.options?.map((opt) => {
                            // Extract letter (A, B, C, D) from start of option string
                            const firstChar = opt.trim().substring(0, 1).toUpperCase();
                            const isSelected = userSelected === firstChar;
                            const isThisCorrect = q.correctAnswer === firstChar;
                            
                            let optionStyles = "border-slate-200 bg-white text-slate-700 hover:border-indigo-200 hover:bg-slate-50";
                            
                            if (userSelected) {
                              if (isThisCorrect) {
                                optionStyles = "border-green-500 bg-green-50/50 text-green-800 ring-1 ring-green-500";
                              } else if (isSelected) {
                                optionStyles = "border-red-400 bg-red-50/50 text-red-800 ring-1 ring-red-400";
                              } else {
                                optionStyles = "border-slate-100 bg-slate-50/30 text-slate-400 cursor-not-allowed";
                              }
                            }

                            return (
                              <button
                                key={opt}
                                disabled={!!userSelected}
                                onClick={() => handleSelectOption(q.id, firstChar)}
                                className={`flex items-start rounded-lg border p-3.5 text-left text-sm font-medium transition duration-150 ${optionStyles}`}
                              >
                                {opt}
                              </button>
                            );
                          })}
                        </div>

                        {/* Interactive Feedback & Explanation block */}
                        {userSelected && (
                          <div className={`rounded-lg p-4 border transition-all duration-300 ${
                            isCorrect ? "border-green-100 bg-green-50/30" : "border-amber-100 bg-amber-50/20"
                          }`}>
                            <div className="flex items-center gap-2 mb-2">
                              {isCorrect ? (
                                <span className="flex h-5 w-5 items-center justify-center rounded-full bg-green-500 text-white">
                                  <Check className="h-3 w-3" />
                                </span>
                              ) : (
                                <span className="flex h-5 w-5 items-center justify-center rounded-full bg-red-500 text-white font-mono text-[10px] font-bold">
                                  X
                                </span>
                              )}
                              <span className={`text-sm font-bold ${isCorrect ? "text-green-800" : "text-amber-800"}`}>
                                {isCorrect ? "Correct Solution!" : `Incorrect. Correct Answer is Option ${q.correctAnswer}`}
                              </span>
                            </div>
                            
                            <div className="border-t border-slate-100 pt-3 mt-2">
                              <span className="text-[10px] font-black uppercase tracking-wider text-slate-500 block mb-1">
                                Step-by-Step Explanation:
                              </span>
                              <p className="text-sm leading-relaxed text-slate-600 font-sans whitespace-pre-line">
                                {q.explanation}
                              </p>
                            </div>
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* LEARNING ROADMAP TAB */}
        {activeTab === "roadmap" && (
          <div className="space-y-6" id="panel-learning-roadmap">
            <div className="flex items-center gap-2">
              <h4 className="text-lg font-bold text-slate-900">Tailored Mastery Roadmap</h4>
              <span className="rounded-full bg-indigo-50 px-2.5 py-0.5 text-xs font-bold text-indigo-700">Chronological Steps</span>
            </div>

            <div className="relative border-l border-slate-200 ml-4 pl-6 space-y-8">
              {aiResponse.learningRoadmap?.map((step) => (
                <div key={step.step} className="relative">
                  {/* Timeline bullet */}
                  <span className="absolute -left-[35px] top-1 flex h-7 w-7 items-center justify-center rounded-full bg-indigo-600 text-xs font-black text-white ring-4 ring-white shadow-sm">
                    {step.step}
                  </span>

                  <div className="rounded-xl border border-slate-100 bg-white p-5 shadow-xs">
                    <div className="flex flex-wrap items-center gap-2 mb-2">
                      <span className="rounded-md bg-indigo-50 px-2 py-0.5 text-xs font-semibold text-indigo-700 uppercase tracking-wider">
                        {step.phase}
                      </span>
                    </div>
                    <h5 className="font-sans font-black text-slate-900 text-base leading-snug">{step.topic}</h5>
                    <p className="mt-2 text-sm leading-relaxed text-slate-600 font-sans">{step.description}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* PREPARATION TIPS TAB */}
        {activeTab === "tips" && (
          <div className="space-y-6" id="panel-prep-tips">
            <div className="flex items-center gap-2">
              <h4 className="text-lg font-bold text-slate-900">Placement Preparation Tips</h4>
              <span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs font-bold text-slate-600">Expert Insights</span>
            </div>

            <div className="grid gap-4 sm:grid-cols-2">
              {aiResponse.preparationTips?.map((tip, index) => (
                <div key={index} className="flex gap-3 rounded-xl border border-slate-100 bg-white p-4.5 shadow-xs">
                  <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-emerald-50 text-emerald-600 mt-0.5">
                    <HelpCircle className="h-4.5 w-4.5" />
                  </span>
                  <p className="text-sm leading-relaxed text-slate-700 font-sans">{tip}</p>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
